name       : libksysguard
version    : 5.21.5
release    : 65
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/libksysguard-5.21.5.tar.xz : 5ff8c687a9d245d28ec4b92c019d2234cd931796c619ebb096de6e49cd18ebe8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
