name       : libksysguard
version    : 5.16.1
release    : 36
source     :
    - https://download.kde.org/stable/plasma/5.16.1/libksysguard-5.16.1.tar.xz : d48fe4623430ca1505674834bbb3632bb9a7e01ef1287155909ff388ed0ca239
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kauth-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - kconfig-devel
        - ki18n-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
