name       : libksysguard
version    : 5.10.5
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.10.5/libksysguard-5.10.5.tar.xz : d6e72c2c01da59c833b08b72b36b667eab2971471e468118e79681e0bbbcac51
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kauth-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - kconfig-devel
        - ki18n-devel
        - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
