name       : libksysguard
version    : 5.16.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/libksysguard-5.16.3.tar.xz : a668348bf1bb65f991d0862fe55c182d852b02ae37ec2ddc88a70fd1477fcf6c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kauth-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - kconfig-devel
        - ki18n-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
