name       : libksysguard
version    : 5.23.4
release    : 75
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.4/libksysguard-5.23.4.tar.xz : 9c1e08cb9a30a23be0485bb015515b271ebbba9a8a00f4a635a226ce152e33f6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
optimize   : lto
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xres)
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - lm_sensors-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
