name       : libksysguard
version    : 5.22.5
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/libksysguard-5.22.5.tar.xz : a522ab976baafa8c1b80cbfe6a4d7718aa8c8623f84294d25c5d43429dd472c2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
optimize   : lto
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xres)
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
