name       : libksysguard
version    : 5.14.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.2/libksysguard-5.14.2.tar.xz : 9dacdb907c3efe4cc4861dc987d8cc24607281651e72e0f8be0116d8b5cb60b3
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kauth-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - kconfig-devel
        - ki18n-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
