name       : libksysguard
version    : 5.12.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.3/libksysguard-5.12.3.tar.xz : f478560119850a8dccfaa00285b7a08a6462b54b31b2a175529e0f889a1e8f1a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kauth-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - kconfig-devel
        - ki18n-devel
        - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
