name       : libksysguard
version    : 5.9.5
release    : 2
source     :
    - https://download.kde.org/stable/plasma/5.9.5/libksysguard-5.9.5.tar.xz : 7c1ed82df3ac46f3fc2e9e0a3bc45cf7d783fae145299e57b7b2e9a2f5dd142c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kauth-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - kconfig-devel
        - ki18n-devel
        - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
