name       : libksysguard
version    : 5.20.5
release    : 60
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/libksysguard-5.20.5.tar.xz : a8a5635c88559567342eba77c707269ab23bc0ce1775ce424c0abd57a83e5d6c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
